apiVersion: v1
kind: Service

metadata:
  name: shellscape-service
  labels:
    app: shellscape

spec:
  type: NodePort

  selector:
    app: shellscape

  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31084